### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by jmszm-dev** [matthijskooijman/arduino-lmic#253] opened 2019-11-10 19:11 UTC
Hi all, 
I've tried to use your LMIC librairy in order to use an SX1276 Lora client.
I've downloaded your librairy on a fresh Arduino IDE install, and meet some compilations problems when using basically samples provided (ABP in my case) .

What was wrong  ? below the end of compilation 
It seems that I'm not the sole guy that append but do not found the solution.
----------------------------------------------------------------------------------------------
C:\Arduino_Croquis\libraries\LMIC-Arduino\src\lmic/lmic.c:405: undefined reference to `table_get_ostime'

C:\Arduino_Croquis\libraries\LMIC-Arduino\src\lmic/lmic.c:407: undefined reference to `table_get_ostime'

C:\Users\jms\AppData\Local\Temp\ccjxmQVb.ltrans0.ltrans.o: In function `initDefaultChannels':

C:\Arduino_Croquis\libraries\LMIC-Arduino\src\lmic/lmic.c:553: undefined reference to `table_get_u4'

C:\Users\jms\AppData\Local\Temp\ccjxmQVb.ltrans0.ltrans.o: In function `radio_irq_handler':

C:\Arduino_Croquis\libraries\LMIC-Arduino\src\lmic/radio.c:777: undefined reference to `table_get_u2'

C:\Users\jms\AppData\Local\Temp\ccjxmQVb.ltrans0.ltrans.o: In function `schedRx12':

C:\Arduino_Croquis\libraries\LMIC-Arduino\src\lmic/lmic.c:1354: undefined reference to `table_get_ostime'

collect2.exe: error: ld returned 1 exit status

---------------------------------------------------------------------------------------------------
Kind regards

**Comment by matthijskooijman** [comment] 2019-11-10 19:36
I think this is a duplicate of #243, so I'm closing this issue. See the other issue for a workaround.

**Closed by matthijskooijman** 2019-11-10 19:36 UTC
