### ISSUE TITLE
Abp node TTGO ESP32 V2

### ISSUE THREAD

**Issue by miguerman** [matthijskooijman/arduino-lmic#209] opened 2018-11-12 09:39 UTC
Hi.
I have the same problem, I have TTGO ESP32 LORA V2, I have configured the mapping pins, and the hal.cpp for SPi.
I am using the ABP example.
Can somebody help me.
Greetings.

Frecuencia 868

Paquetes en cola 
96386060: EV_TXCOMPLETE (incluye la espera de ventanas RX) 
de paquetes en cola 
96829613: EV_TXCOMPLETE (incluye la espera de ventanas RX) 
de paquetes en cola 
97273165: EV_TXCOMPLETE (incluye la espera de ventanas RX) 
de paquetes en cola 
97716714: EV_TXCOMPLETE (incluye la espera de ventanas RX) 
de paquetes en cola 
98160266: EV_TXCOMPLETE (incluye esperar las ventanas de RX) 
Paquete en cola 
98603888: EV_TXCOMPLETE (incluye esperar las ventanas de RX

I'm sorry I doubled the question.

**Comment by matthijskooijman** [comment] 2018-11-12 11:16
I'm closing this as a duplicate of #201, where you also commented. I don't have time to help debug this in detail, perhaps you could ask on the TTN forums? Be sure to include more details about your setup if you do (e.g. are you sure you have gateway coverage, are you using OTAA or ABP, did you double-check the encryption keys and Ids etc).

**Closed by matthijskooijman** 2018-11-12 11:16 UTC
